# DO NOT EDIT. generated with 'nim r tools/gencommands2.nim > compiler/front/commands2.nim'

import std/options

type
  CliOptKind* {.pure.} = enum
    set # set or unset
    boolean # --foo:on and --foo:off

  CliOptDef* = object
    name*: string
    ## if empty, then it doesn't have short version
    short*: Option[char]
    ## if empty, then it doesn't have long version
    long*: Option[string]
    ## what kind of switch it is
    kind*: CliOptKind

const allCliOptions* = [

CliOptDef(name: "Fromcmd",
  long: some "fromcmd",
  kind: CliOptKind.set, ),
CliOptDef(name: "Path",
  short: some 'p',
  long: some "path",
  kind: CliOptKind.set, ),
CliOptDef(name: "Nimblepath",
  long: some "nimblepath",
  kind: CliOptKind.set, ),
CliOptDef(name: "Nonimblepath",
  long: some "nonimblepath",
  kind: CliOptKind.set, ),
CliOptDef(name: "Clearnimblepath",
  long: some "clearnimblepath",
  kind: CliOptKind.set, ),
CliOptDef(name: "Excludepath",
  long: some "excludepath",
  kind: CliOptKind.set, ),
CliOptDef(name: "Nimcache",
  long: some "nimcache",
  kind: CliOptKind.set, ),
CliOptDef(name: "Out",
  short: some 'o',
  long: some "out",
  kind: CliOptKind.set, ),
CliOptDef(name: "Outdir",
  long: some "outdir",
  kind: CliOptKind.set, ),
CliOptDef(name: "Depfile",
  long: some "depfile",
  kind: CliOptKind.set, ),
CliOptDef(name: "Usenimcache",
  long: some "usenimcache",
  kind: CliOptKind.set, ),
CliOptDef(name: "Docseesrcurl",
  long: some "docseesrcurl",
  kind: CliOptKind.set, ),
CliOptDef(name: "Docroot",
  long: some "docroot",
  kind: CliOptKind.set, ),
CliOptDef(name: "Backend",
  short: some 'b',
  long: some "backend",
  kind: CliOptKind.set, ),
CliOptDef(name: "Doccmd",
  long: some "doccmd",
  kind: CliOptKind.set, ),
CliOptDef(name: "Define",
  short: some 'd',
  long: some "define",
  kind: CliOptKind.set, ),
CliOptDef(name: "Undef",
  short: some 'u',
  long: some "undef",
  kind: CliOptKind.set, ),
CliOptDef(name: "Compile",
  long: some "compile",
  kind: CliOptKind.set, ),
CliOptDef(name: "Link",
  long: some "link",
  kind: CliOptKind.set, ),
CliOptDef(name: "Debuginfo",
  long: some "debuginfo",
  kind: CliOptKind.set, ),
CliOptDef(name: "Embedsrc",
  long: some "embedsrc",
  kind: CliOptKind.set, ),
CliOptDef(name: "Compileonly",
  short: some 'c',
  long: some "compileonly",
  kind: CliOptKind.set, ),
CliOptDef(name: "Nolinking",
  long: some "nolinking",
  kind: CliOptKind.set, ),
CliOptDef(name: "Nomain",
  long: some "nomain",
  kind: CliOptKind.set, ),
CliOptDef(name: "Forcebuild",
  short: some 'f',
  long: some "forcebuild",
  kind: CliOptKind.set, ),
CliOptDef(name: "Project",
  long: some "project",
  kind: CliOptKind.set, ),
CliOptDef(name: "Gc",
  long: some "gc",
  kind: CliOptKind.set, ),
CliOptDef(name: "Warnings",
  short: some 'w',
  long: some "warnings",
  kind: CliOptKind.set, ),
CliOptDef(name: "Warning",
  long: some "warning",
  kind: CliOptKind.set, ),
CliOptDef(name: "Hint",
  long: some "hint",
  kind: CliOptKind.set, ),
CliOptDef(name: "Warningaserror",
  long: some "warningaserror",
  kind: CliOptKind.set, ),
CliOptDef(name: "Hintaserror",
  long: some "hintaserror",
  kind: CliOptKind.set, ),
CliOptDef(name: "Hints",
  long: some "hints",
  kind: CliOptKind.set, ),
CliOptDef(name: "Threadanalysis",
  long: some "threadanalysis",
  kind: CliOptKind.set, ),
CliOptDef(name: "Stacktrace",
  long: some "stacktrace",
  kind: CliOptKind.set, ),
CliOptDef(name: "Stacktracemsgs",
  long: some "stacktracemsgs",
  kind: CliOptKind.set, ),
CliOptDef(name: "Excessivestacktrace",
  long: some "excessivestacktrace",
  kind: CliOptKind.set, ),
CliOptDef(name: "Linetrace",
  long: some "linetrace",
  kind: CliOptKind.set, ),
CliOptDef(name: "Debugger",
  long: some "debugger",
  kind: CliOptKind.set, ),
CliOptDef(name: "Profiler",
  long: some "profiler",
  kind: CliOptKind.set, ),
CliOptDef(name: "Memtracker",
  long: some "memtracker",
  kind: CliOptKind.set, ),
CliOptDef(name: "Checks",
  long: some "checks",
  kind: CliOptKind.set, ),
CliOptDef(name: "Floatchecks",
  long: some "floatchecks",
  kind: CliOptKind.set, ),
CliOptDef(name: "Infchecks",
  long: some "infchecks",
  kind: CliOptKind.set, ),
CliOptDef(name: "Nanchecks",
  long: some "nanchecks",
  kind: CliOptKind.set, ),
CliOptDef(name: "Objchecks",
  long: some "objchecks",
  kind: CliOptKind.set, ),
CliOptDef(name: "Fieldchecks",
  long: some "fieldchecks",
  kind: CliOptKind.set, ),
CliOptDef(name: "Rangechecks",
  long: some "rangechecks",
  kind: CliOptKind.set, ),
CliOptDef(name: "Boundchecks",
  long: some "boundchecks",
  kind: CliOptKind.set, ),
CliOptDef(name: "Overflowchecks",
  long: some "overflowchecks",
  kind: CliOptKind.set, ),
CliOptDef(name: "Staticboundchecks",
  long: some "staticboundchecks",
  kind: CliOptKind.set, ),
CliOptDef(name: "Stylechecks",
  long: some "stylechecks",
  kind: CliOptKind.set, ),
CliOptDef(name: "Linedir",
  long: some "linedir",
  kind: CliOptKind.set, ),
CliOptDef(name: "Assertions",
  long: some "assertions",
  kind: CliOptKind.set, ),
CliOptDef(name: "Threads",
  long: some "threads",
  kind: CliOptKind.set, ),
CliOptDef(name: "Tlsemulation",
  long: some "tlsemulation",
  kind: CliOptKind.set, ),
CliOptDef(name: "Implicitstatic",
  long: some "implicitstatic",
  kind: CliOptKind.set, ),
CliOptDef(name: "Trmacros",
  long: some "trmacros",
  kind: CliOptKind.set, ),
CliOptDef(name: "Opt",
  long: some "opt",
  kind: CliOptKind.set, ),
CliOptDef(name: "App",
  long: some "app",
  kind: CliOptKind.set, ),
CliOptDef(name: "Passc",
  long: some "passc",
  kind: CliOptKind.set, ),
CliOptDef(name: "Passl",
  long: some "passl",
  kind: CliOptKind.set, ),
CliOptDef(name: "Cincludes",
  long: some "cincludes",
  kind: CliOptKind.set, ),
CliOptDef(name: "Clibdir",
  long: some "clibdir",
  kind: CliOptKind.set, ),
CliOptDef(name: "Clib",
  long: some "clib",
  kind: CliOptKind.set, ),
CliOptDef(name: "Header",
  long: some "header",
  kind: CliOptKind.set, ),
CliOptDef(name: "Index",
  long: some "index",
  kind: CliOptKind.set, ),
CliOptDef(name: "Import",
  long: some "import",
  kind: CliOptKind.set, ),
CliOptDef(name: "Include",
  long: some "include",
  kind: CliOptKind.set, ),
CliOptDef(name: "Listcmd",
  long: some "listcmd",
  kind: CliOptKind.set, ),
CliOptDef(name: "Asm",
  long: some "asm",
  kind: CliOptKind.set, ),
CliOptDef(name: "Genmapping",
  long: some "genmapping",
  kind: CliOptKind.set, ),
CliOptDef(name: "Os",
  long: some "os",
  kind: CliOptKind.set, ),
CliOptDef(name: "Cpu",
  long: some "cpu",
  kind: CliOptKind.set, ),
CliOptDef(name: "Run",
  long: some "run",
  kind: CliOptKind.set, ),
CliOptDef(name: "Maxloopiterationsvm",
  long: some "maxloopiterationsvm",
  kind: CliOptKind.set, ),
CliOptDef(name: "Errormax",
  long: some "errormax",
  kind: CliOptKind.set, ),
CliOptDef(name: "Verbosity",
  long: some "verbosity",
  kind: CliOptKind.set, ),
CliOptDef(name: "Parallelbuild",
  long: some "parallelbuild",
  kind: CliOptKind.set, ),
CliOptDef(name: "Version",
  short: some 'v',
  long: some "version",
  kind: CliOptKind.set, ),
CliOptDef(name: "Advanced",
  long: some "advanced",
  kind: CliOptKind.set, ),
CliOptDef(name: "Fullhelp",
  long: some "fullhelp",
  kind: CliOptKind.set, ),
CliOptDef(name: "Help",
  short: some 'h',
  long: some "help",
  kind: CliOptKind.set, ),
CliOptDef(name: "Incremental",
  long: some "ic'",
  kind: CliOptKind.set, ),
CliOptDef(name: "Skipcfg",
  long: some "skipcfg",
  kind: CliOptKind.set, ),
CliOptDef(name: "Skipprojcfg",
  long: some "skipprojcfg",
  kind: CliOptKind.set, ),
CliOptDef(name: "Skipusercfg",
  long: some "skipusercfg",
  kind: CliOptKind.set, ),
CliOptDef(name: "Skipparentcfg",
  long: some "skipparentcfg",
  kind: CliOptKind.set, ),
CliOptDef(name: "Genscript",
  long: some "genscript",
  kind: CliOptKind.set, ),
CliOptDef(name: "Colors",
  long: some "colors",
  kind: CliOptKind.set, ),
CliOptDef(name: "Lib",
  long: some "lib",
  kind: CliOptKind.set, ),
CliOptDef(name: "Putenv",
  long: some "putenv",
  kind: CliOptKind.set, ),
CliOptDef(name: "Cc",
  long: some "cc",
  kind: CliOptKind.set, ),
CliOptDef(name: "Stdout",
  long: some "stdout",
  kind: CliOptKind.set, ),
CliOptDef(name: "Filenames",
  long: some "filenames",
  kind: CliOptKind.set, ),
CliOptDef(name: "Msgformat",
  long: some "msgformat",
  kind: CliOptKind.set, ),
CliOptDef(name: "Processing",
  long: some "processing",
  kind: CliOptKind.set, ),
CliOptDef(name: "Unitsep",
  long: some "unitsep",
  kind: CliOptKind.set, ),
CliOptDef(name: "Listfullpaths",
  long: some "listfullpaths",
  kind: CliOptKind.set, ),
CliOptDef(name: "Spellsuggest",
  long: some "spellsuggest",
  kind: CliOptKind.set, ),
CliOptDef(name: "Declaredlocs",
  long: some "declaredlocs",
  kind: CliOptKind.set, ),
CliOptDef(name: "Dynliboverride",
  long: some "dynliboverride",
  kind: CliOptKind.set, ),
CliOptDef(name: "Dynliboverrideall",
  long: some "dynliboverrideall",
  kind: CliOptKind.set, ),
CliOptDef(name: "Experimental",
  long: some "experimental",
  kind: CliOptKind.set, ),
CliOptDef(name: "Exceptions",
  long: some "exceptions",
  kind: CliOptKind.set, ),
CliOptDef(name: "Cppdefine",
  long: some "cppdefine",
  kind: CliOptKind.set, ),
CliOptDef(name: "Seqsv2",
  long: some "seqsv2",
  kind: CliOptKind.set, ),
CliOptDef(name: "Stylecheck",
  long: some "stylecheck",
  kind: CliOptKind.set, ),
CliOptDef(name: "Showallmismatches",
  long: some "showallmismatches",
  kind: CliOptKind.set, ),
CliOptDef(name: "Docinternal",
  long: some "docinternal",
  kind: CliOptKind.set, ),
CliOptDef(name: "Multimethods",
  long: some "multimethods",
  kind: CliOptKind.set, ),
CliOptDef(name: "Expandmacro",
  long: some "expandmacro",
  kind: CliOptKind.set, ),
CliOptDef(name: "Expandarc",
  long: some "expandarc",
  kind: CliOptKind.set, ),
CliOptDef(name: "Benchmarkvm",
  long: some "benchmarkvm",
  kind: CliOptKind.set, ),
CliOptDef(name: "Profilevm",
  long: some "profilevm",
  kind: CliOptKind.set, ),
CliOptDef(name: "Sinkinference",
  long: some "sinkinference",
  kind: CliOptKind.set, ),
CliOptDef(name: "Cursorinference",
  long: some "cursorinference",
  kind: CliOptKind.set, ),
CliOptDef(name: "Panics",
  long: some "panics",
  kind: CliOptKind.set, ),
CliOptDef(name: "Sourcemap",
  long: some "sourcemap",
  kind: CliOptKind.set, ),
CliOptDef(name: "Deepcopy",
  long: some "deepcopy",
  kind: CliOptKind.set, ),
CliOptDef(name: "ProjStdin",
  kind: CliOptKind.set, ),
CliOptDef(name: "Cmdexitgcstats",
  long: some "cmdexitgcstats",
  kind: CliOptKind.set, ),
CliOptDef(name: "ConfigVar",
  long: some "*.*",
  kind: CliOptKind.set, ),
]
